all:
	@echo "Write this Makefile by your self."

sim-verilator-tracing-C:
	$(call git_commit, "sim RTL") # DO NOT REMOVE THIS LINE!!!
	$(MAKE) -C ../verilator-test/make_tracing_c run

include ../Makefile
